  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: webserver
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - /home/ubuntu/rstudio_docker/nginx.conf:/etc/nginx/nginx.conf
      - dbdata:/ssl/


